Algoritmo "Aluno"
//calcular a média de um aluno
Var
// Seção de Declarações das variáveis 
nota1,nota2,media = real
Inicio
escreva("primeira nota do aluno")
leia (nota1)
escreva("segunda nota do aluno")
leia (nota2)
media <- (nota1 + nota2)/2
escreva("a méda do aluno é", media)
se (media>=6) então
escreva ("aluno foi aprovado")
senao
escreva ("sefudeu neguin")
fimse

Fimalgoritmo